---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  selector:
    app: testapp
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: alexdvps/testapp:latest
          readinessProbe:
              httpGet:
                path: /health
                port: 3000
              initialDelaySeconds: 5
              periodSeconds: 3
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: testapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testapp
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
